# Streamlit secrets configuration
# Add any API keys or sensitive configuration here
# Note: This is a template - actual secrets should be configured in Streamlit Cloud UI

# Example:
# [database]
# username = "your_username"
# password = "your_password"

# [api_keys]
# tmdb_api_key = "your_api_key"
